### ISSUE TITLE
Firebase service account for Docker

### ISSUE THREAD

**Issue by brian-nguyen** [ubclaunchpad/bumper#233]
The production container should have a copy of the service account credentials in the final stage. Also investigate whether or not the `vendor/` directory is being updated properly.

**Comment by bobheadxi** [comment]
yeah you'll want to remove [this](https://github.com/ubclaunchpad/bumper/blob/master/Dockerfile#L16) and add `vendor` to your `.dockerignore`, my bad: 😋 

```bash
RUN if [ ! -d "vendor" ]; then \
    go get -u github.com/golang/dep/cmd/dep; \
    dep ensure; \
    fi
```

Some history behind this decision - Docker caching for this layer seemed a bit finnicky, and since all [Inertia](https://github.com/ubclaunchpad/inertia) builds are done either a) manually with `dep ensure` beforehand or b) automatically via Travis but with a fresh `dep ensure`, I added this condition so that if a `vendor` directory is mounted then Docker would 100% skip the potentially lengthy `dep` operations.

Didn't think too much of it when I added the configuration to Bumper, but in continuous deployment via Inertia, your vendor directory will never get updated if one exists already 😢
